-- EngStep v3 / Supabase schema
-- Supabase SQL Editor에서 1회 실행합니다.

create table if not exists public.books (
  book_id text primary key,
  version integer not null default 1,
  title text not null,
  content_type text not null check (content_type in ('vocab','grammar')),
  is_published boolean not null default false,
  pack jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_id text not null,
  question_id text not null,
  content_type text not null check (content_type in ('vocab','grammar')),
  book_id text not null,
  book_title text not null default '',
  unit_key text not null,
  question_index integer not null,
  is_correct boolean not null,
  given_answer text not null default '',
  study_mode text not null default 'unit',
  answered_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique(user_id, client_id)
);

create index if not exists attempts_user_answered_idx
  on public.attempts(user_id, answered_at desc);
create index if not exists attempts_user_question_idx
  on public.attempts(user_id, question_id);

alter table public.books enable row level security;
alter table public.attempts enable row level security;

drop policy if exists "published books readable" on public.books;
create policy "published books readable"
on public.books for select
using (is_published = true);

drop policy if exists "users read own attempts" on public.attempts;
create policy "users read own attempts"
on public.attempts for select
using (auth.uid() = user_id);

drop policy if exists "users insert own attempts" on public.attempts;
create policy "users insert own attempts"
on public.attempts for insert
with check (auth.uid() = user_id);

drop policy if exists "users update own attempts" on public.attempts;
create policy "users update own attempts"
on public.attempts for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- books의 추가/수정/게시 권한은 학생 클라이언트에 주지 않습니다.
-- 새 교재는 관리자 환경에서 pack JSON을 books.pack에 넣고 is_published=true로 게시합니다.
